spring.application.name=network-statistic

#logging.level.root=debug

# enable virtual thread for all
spring.threads.virtual.enabled=true

# Display SQL in the console
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG