# config quartz as scheduler/scheduler/admin only
config-as-scheduler=true

# change server port
server.port=8081

# use tomcat in scheduler mode
spring.main.web-application-type=servlet

# all profiles define scheduler DB
# quartz datasource config, for jobstore
spring.datasource.quartz-scheduler.jdbcUrl=jdbc:mysql://mysql1:3306/quartz?connectionTimeZone=UTC
spring.datasource.quartz-scheduler.username=quartz
spring.datasource.quartz-scheduler.password=abc123
# auto commit false could reduce setting autocommit=1 per connection
spring.datasource.quartz-scheduler.autoCommit=false
spring.datasource.quartz-scheduler.connectionTimeout=120000
# set read commit transaction
spring.datasource.quartz-scheduler.transactionIsolation=2
# should set to number of job + 3
spring.datasource.quartz-scheduler.maximumPoolSize=3

# config app datasource
spring.datasource.statistic-db.jdbcUrl=jdbc:mysql://mysql1:3306/network_statistics?connectionTimeZone=UTC
spring.datasource.statistic-db.username=dev
spring.datasource.statistic-db.password=abc123
# for statistic etl, need to use autocommit
spring.datasource.statistic-db.autoCommit=true
spring.datasource.statistic-db.connectionTimeout=120000
# set read commit transaction
spring.datasource.statistic-db.transactionIsolation=2
# set to number of concurrent job (admin mode does not need significant connections)
spring.datasource.statistic-db.maximumPoolSize=2
# optimized config :)   https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
spring.datasource.statistic-db.dataSourceProperties.cachePrepStmts=true
spring.datasource.statistic-db.dataSourceProperties.prepStmtCacheSize=250
spring.datasource.statistic-db.dataSourceProperties.prepStmtCacheSqlLimit=2048
spring.datasource.statistic-db.dataSourceProperties.useServerPrepStmts=true
spring.datasource.statistic-db.dataSourceProperties.useLocalSessionState=true
spring.datasource.statistic-db.dataSourceProperties.rewriteBatchedStatements=true
spring.datasource.statistic-db.dataSourceProperties.cacheResultSetMetadata=true
spring.datasource.statistic-db.dataSourceProperties.cacheServerConfiguration=true
spring.datasource.statistic-db.dataSourceProperties.elideSetAutoCommits=true
spring.datasource.statistic-db.dataSourceProperties.maintainTimeStats=false

# config app jpa properties
spring.jpa.statistic-db.hibernate.hbm2ddl.auto=none
spring.jpa.statistic-db.hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
spring.jpa.statistic-db.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

